
version: '3.1'

services:
        sqldb:
                image: mysql:5.7
                volumes:
                        - sql_volume_new1:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: user
                        MYSQL_PASSWORD: pass
                        MYSQL_DATABASE: dbase
        drupal:
                image: drupal:8-apache
                ports:
                       - 8080:80
                restart: always
                volumes:
                       - drupal-modules:/var/www/html/modules
                       - drupal-profiles:/var/www/html/profiles
                       - drupal-sites:/var/www/html/sites
                       - drupal-themes:/var/www/html/themes
                depends_on:
                       - dbos
                environment:
                        DRUPAL_DATABASE_NAME: dbase
                        DRUPAL_DATABASE_USERNAME: user
                        DRUPAL_DATABASE_PASSWORD: pass
volumes:
        drupal-modules:
        drupal-profiles:
        drupal-sites:
        drupal-themes:
        sql_volume_new1:
~                                                                                                                                                                                                           
~                                                                                                                                                                                                           
~                                                                                                                                                                                                           
~                                                                                                                                                                                                           
~                                                                                                                                                                                                           
~                                                                                                                                                                                                           
~
